name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행
    paths:
      - 'main.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/google-cloud-run-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: '${{ secrets.GCP_SERVICE_NAME }}'
          region: 'asia-northeast3' # 서울 리전
          image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:${{ github.sha }}'
          platform: 'managed'
          allow_unauthenticated: true # 모든 사용자가 접근 가능하도록 설정
          # ✨ 여기가 수정된 부분입니다.
          # 컨테이너에 환경 변수를 전달합니다.
          env_vars:
            GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
