name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/google-cloud-run-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}/${{ secrets.GCP_SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: '${{ secrets.GCP_SERVICE_NAME }}'
          region: 'asia-northeast3'
          image: 'asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}/${{ secrets.GCP_SERVICE_NAME }}:${{ github.sha }}'
          # --- ✨ 여기가 수정된 부분입니다 ✨ ---
          # 1. 서비스 계정을 직접 지정합니다.
          #    (이메일 주소 전체를 입력해야 합니다.)
          service_account: 'sheet-writer-backend@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
          # 2. 더 이상 필요 없는 env_vars 부분을 완전히 제거했습니다.
          flags: '--platform=managed --allow-unauthenticated'
          # --- ✨ 수정된 부분 끝 ---
